### ISSUE TITLE
FunnyGames fails test case 9

### ISSUE THREAD

**Issue by SethKitchen** [TimonKnigge/Competitive-Programming#1]
I am having the same issue with Kattis that your code has. Times out on test case 9. I really want to know what case that is.

**Comment by TimonKnigge** [comment]
Hi, thanks for letting me know. It used to pass, but it seems the people at Kattis occassionally strengthen the testcases (I've had this problem before). Testcase 9 is presumably the first 'large' testcase. Notice that if all the F_k are close to .9, you'll end up with a ton of very small intervals, something my old solution handled poorly.

I ended up rewriting my solution, it uses some similar ideas but there are some noticable differences. Feel free to use it as inspiration.

**Comment by SethKitchen** [comment]
Thanks your files really help me become a better programmer. Please keep up your awesomeness!

**Comment by TimonKnigge** [comment]
Good to hear, thanks! :)
